using GBSharp.Backend.GBDK.Reporting;

namespace GBSharp.Tests.Backend;

/// <summary>
/// Turning a running address back into the C# that produced it. These run
/// without GBDK and without the emulator: the two artefacts are written here as
/// literals, in the format a real build produces, so what the resolver relies
/// on is visible in the test rather than buried in a fixture.
/// </summary>
public sealed class RomSymbolResolverTests : IDisposable
{
    /// <summary>
    /// A linker map in GBDK's format. Deliberately not in address order, and
    /// with a data symbol between two functions, which is what a real one looks
    /// like.
    /// </summary>
    private const string SymbolMap = """
        ; Generated by GB# tests
        00:0150 _main
        03:4100 _EnemySystem_Update
        03:4000 _PlayerSystem_Update
        03:41C0 _s_enemy_table
        03:4240 _gbs_list_add
        """;

    private const string FunctionMap = """
        [
          { "name": "main", "method": "Program.Main", "file": "C:\\game\\Program.cs", "line": 7 },
          { "name": "PlayerSystem_Update", "method": "PlayerSystem.Update", "file": "C:\\game\\PlayerSystem.cs", "line": 18 },
          { "name": "EnemySystem_Update", "method": "EnemySystem.Update", "file": "C:\\game\\EnemySystem.cs", "line": 42 },
          { "name": "gbs_list_add" }
        ]
        """;

    private readonly string directory =
        Directory.CreateTempSubdirectory("gbsharp-symbols-").FullName;

    private RomSymbolResolver Resolver(string? symbols = SymbolMap, string? functions = FunctionMap)
    {
        string symbolPath = Path.Combine(directory, "game.sym");
        string functionPath = Path.Combine(directory, "game.functions.json");

        if (symbols is not null)
        {
            File.WriteAllText(symbolPath, symbols);
        }

        if (functions is not null)
        {
            File.WriteAllText(functionPath, functions);
        }

        return RomSymbolResolver.Load(symbolPath, functionPath);
    }

    [Fact]
    public void AnAddressInsideAFunctionResolvesToTheMethodThatProducedIt()
    {
        // The whole chain, and the only assertion in here that matters: an
        // address the CPU could actually be at, named as C#.
        CodeLocation? location = Resolver().Resolve(3, 0x4121);

        Assert.NotNull(location);
        Assert.Equal("EnemySystem_Update", location.Symbol);
        Assert.Equal("EnemySystem.Update", location.Method);
        Assert.Equal(42, location.Line);
        Assert.EndsWith("EnemySystem.cs", location.File);
        Assert.Equal(0x21, location.Offset);
    }

    [Fact]
    public void AnAddressOnASymbolIsThatSymbolWithNoOffset()
    {
        CodeLocation? location = Resolver().Resolve(3, 0x4000);

        Assert.NotNull(location);
        Assert.Equal("PlayerSystem_Update", location.Symbol);
        Assert.Equal(0, location.Offset);
    }

    [Fact]
    public void TheNearestSymbolWinsRatherThanTheFirstOneListed()
    {
        // 0x4200 is past the data symbol at 0x41C0 and short of the function at
        // 0x4240, so a resolver that searched the file in order, or that kept
        // only functions, would answer EnemySystem_Update. Being wrong quietly
        // is the failure mode this whole class exists to avoid.
        CodeLocation? location = Resolver().Resolve(3, 0x4200);

        Assert.NotNull(location);
        Assert.Equal("s_enemy_table", location.Symbol);
        Assert.Null(location.Method);
    }

    [Fact]
    public void ACompilerGeneratedFunctionIsNamedButHasNoMethod()
    {
        // GB# wrote it, so there is no C# line to point at. Saying so beats
        // reporting nothing, which would be indistinguishable from an address
        // that resolved to no symbol at all.
        CodeLocation? location = Resolver().Resolve(3, 0x4250);

        Assert.NotNull(location);
        Assert.Equal("gbs_list_add", location.Symbol);
        Assert.Null(location.Method);
        Assert.Null(location.File);
    }

    [Fact]
    public void BanksDoNotLeakIntoEachOther()
    {
        // Bank 3's symbols start at 0x4000 and bank 0's at 0x0150. Asking bank
        // 0 about a banked address must not fall back on bank 3's answer: two
        // banks hold different code at the same address, which is the point of
        // banking.
        Assert.Null(Resolver().Resolve(0, 0x4121));
    }

    [Fact]
    public void AnAddressBelowEverySymbolResolvesToNothing()
    {
        Assert.Null(Resolver().Resolve(0, 0x0100));
    }

    [Fact]
    public void AnAddressOutsideTheCartridgeResolvesToNothing()
    {
        // What GameBoy.RomBankAt reports for HRAM, where a bank-switching
        // trampoline runs. A real case, not a defensive one.
        Assert.Null(Resolver().Resolve(-1, 0xFF80));
    }

    [Fact]
    public void AMissingFunctionMapStillNamesTheSymbol()
    {
        CodeLocation? location = Resolver(functions: null).Resolve(3, 0x4121);

        Assert.NotNull(location);
        Assert.Equal("EnemySystem_Update", location.Symbol);
        Assert.Null(location.Method);
    }

    [Fact]
    public void AMissingSymbolMapResolvesNothingRatherThanThrowing()
    {
        RomSymbolResolver resolver = Resolver(symbols: null);

        Assert.True(resolver.IsEmpty);
        Assert.Null(resolver.Resolve(3, 0x4121));
    }

    [Fact]
    public void ADamagedFunctionMapDegradesToSymbolsRatherThanThrowing()
    {
        CodeLocation? location = Resolver(functions: "{ not json").Resolve(3, 0x4121);

        Assert.NotNull(location);
        Assert.Equal("EnemySystem_Update", location.Symbol);
        Assert.Null(location.Method);
    }

    [Fact]
    public void TheTextFormReadsAsAPlaceInTheDevelopersSource()
    {
        Assert.Equal(
            "03:4121 EnemySystem_Update+33 - EnemySystem.Update (EnemySystem.cs:42)",
            Resolver().Resolve(3, 0x4121)!.ToString());
    }

    [Fact]
    public void ForRomFindsBothArtefactsFromTheRomItself()
    {
        // How a caller actually gets one: it has the ROM, and the linker named
        // everything else after it.
        Resolver();
        File.WriteAllBytes(Path.Combine(directory, "game.gb"), [0]);

        CodeLocation? location =
            RomSymbolResolver.ForRom(Path.Combine(directory, "game.gb")).Resolve(3, 0x4121);

        Assert.NotNull(location);
        Assert.Equal("EnemySystem.Update", location.Method);
    }

    public void Dispose()
    {
        try
        {
            Directory.Delete(directory, recursive: true);
        }
        catch (IOException)
        {
            // A leftover temp directory is not worth failing a test over.
        }
    }
}
